### ISSUE TITLE
Mutating admission controller doesn't handle annotations that contain '/'

### ISSUE THREAD

**Issue by teq0** [open-policy-agent/library#25]
When adding a patch for an annotation with a path like `/metadata/annotations/kubernetes.io/role` the annotation isn't added, and any existing annotations are removed.
This happens whether or not there are any existing annotations in that path.

**Comment by tsandall** [comment]
This has to do with how [JSON Pointer (RFC 6901)](https://tools.ietf.org/html/rfc6901) handles escaping of `/` characters. JSON Patch uses JSON Pointer to model the `path` field in the patch operation.

The `/` in `kubernetes.io/role` needs to be escaped. The path in the patch ought to be: `/metadata/annotations/kubernetes.io~1role`.
